# Generated by Django 3.2.4 on 2021-07-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de las imagenes')),
                ('ruta', models.CharField(max_length=50, verbose_name='Ruta de la imagen')),
            ],
        ),
    ]
