# Generated by Django 3.2.5 on 2021-07-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('correoacceso', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Correo')),
                ('passwordacceso', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('subir_imagen', models.ImageField(null=True, upload_to='confirma_imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imagenes')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('contenido', models.CharField(max_length=50, unique=True)),
                ('sub_title', models.CharField(max_length=100, unique=True)),
                ('idImagen', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de las imagenes')),
                ('subir_imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipousuario', models.AutoField(primary_key=True, serialize=False, verbose_name='idtipousuario')),
                ('ntipousuario', models.CharField(max_length=50, verbose_name='TipoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nusuario', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('ncompleto', models.CharField(max_length=100, verbose_name='NombreCompleto')),
                ('correo', models.EmailField(max_length=500, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Idusuario')),
                ('tipoUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
    ]
