# Generated by Django 3.2.4 on 2021-07-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipousuario', models.AutoField(primary_key=True, serialize=False, verbose_name='idtipousuario')),
                ('ntipousuario', models.CharField(max_length=50, verbose_name='TipoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Idusuario')),
                ('ncompleto', models.CharField(max_length=100, verbose_name='NombreCompleto')),
                ('correo', models.EmailField(max_length=500, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
    ]
