# Generated by Django 3.2.4 on 2021-07-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipousuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('correoacceso', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Correo')),
                ('passwordacceso', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario'),
        ),
    ]
