# Generated by Django 3.2.5 on 2021-07-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210712_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
