# Generated by Django 3.2.5 on 2021-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='subir_imagen',
            field=models.ImageField(null=True, upload_to='confirma_imagen'),
        ),
    ]
