# Generated by Django 3.2.5 on 2021-07-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imagen_subir_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='subir_imagen',
            field=models.ImageField(null=True, upload_to='foto usuario'),
        ),
    ]
