# Generated by Django 3.2.5 on 2021-07-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_subir_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='subir_imagen',
        ),
        migrations.AddField(
            model_name='acceso',
            name='subir_imagen',
            field=models.ImageField(null=True, upload_to='confirma_imagen'),
        ),
    ]
