# Generated by Django 3.2.5 on 2021-07-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210712_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='subir_imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
