# Generated by Django 3.2.5 on 2021-07-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_imagen_subir_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='subir_imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
