# Generated by Django 3.2.5 on 2021-07-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_imagen_subir_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={},
        ),
        migrations.AddField(
            model_name='imagen',
            name='contenido',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
