# Generated by Django 3.2.5 on 2021-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210712_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='contenido',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
